import type { Job } from '../../types/app';

export const mockJobs: Job[] = [
  {
    id: 'job-1',
    vehicle: '2022 Honda CR-V',
    roNumber: '25481',
    customerName: 'Maria Lopez',
    amount: 5600,
    amountStatus: 'notFinal',
    status: 'inProgress',
    done: false,
    promiseDate: '2026-03-18',
    partsWaiting: true,
    textNotes: [
      {
        id: 'note-1',
        type: 'text',
        text: 'Check blend on the left rear door.',
        createdAt: '2026-03-15T09:20:00',
        read: false,
      },
    ],
  },
  {
    id: 'job-2',
    vehicle: '2021 Toyota Camry',
    roNumber: '25482',
    customerName: 'James Porter',
    amount: 3200,
    amountStatus: 'final',
    status: 'waiting',
    done: false,
    promiseDate: '2026-03-19',
    partsWaiting: false,
    textNotes: [],
  },
  {
    id: 'job-3',
    vehicle: '2023 Nissan Altima',
    roNumber: '25483',
    customerName: 'Stephanie Cruz',
    amount: 4100,
    amountStatus: 'notFinal',
    status: 'notStarted',
    done: false,
    promiseDate: '2026-03-21',
    partsWaiting: false,
    textNotes: [
      {
        id: 'note-2',
        type: 'text',
        text: 'Customer may call about pickup timing.',
        createdAt: '2026-03-15T10:05:00',
        read: false,
      },
    ],
  },
  {
    id: 'job-4',
    vehicle: '2020 Ford Escape',
    roNumber: '25460',
    customerName: 'Derrick Hall',
    amount: 2850,
    amountStatus: 'final',
    status: 'done',
    done: true,
    promiseDate: '2026-03-14',
    partsWaiting: false,
    textNotes: [
      {
        id: 'note-3',
        type: 'text',
        text: 'Vehicle washed and ready for pickup.',
        createdAt: '2026-03-14T14:30:00',
        read: true,
      },
    ],
  },
];